project:
  type: website

website:
  title: "Jingya Wang"
  google-analytics: "G-7F1M5KXHG4"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Impact
        href: impact.qmd
      - text: Teaching & Service
        href: teaching.qmd
      - text: Awards & Funding
        href: awards.qmd
      - text: Outside the lab
        href: outside.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: article